[package]
name = "ar-glass-screen"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.16.3", features = ["derive"] }
crabgrab = { git = "https://github.com/tana/CrabGrab.git", rev = "8d927700700fb1c01d35878a44ebb6c05070a431", features = ["wgpu"] }
env_logger = "0.11.5"
log = "0.4.22"
pollster = "0.3.0"
wgpu = "22.0.0"
winit = "0.30.4"

[patch.crates-io]